### ISSUE TITLE
_fuzzy_eq?

### ISSUE THREAD

**Issue by jordiae** [guyd1995/embedding-space#3]
Hi! Do you know what the function `_fuzzy_eq()` used once in the notebooks was supposed to do? The function is not defined.

Thanks!

**Comment by dar-tau** [comment]
Hi Jordi
Yes, the function was used to remove "soft duplicates" from the token list, by edit distance or something of this sort.
I think I deleted the cell by mistake and the need wasn't strong enough to warrant writing it again

**Comment by jordiae** [comment]
Got it, thanks!
